### ISSUE TITLE
Add deletion operation in BST

### ISSUE THREAD

**Issue by tirthasheshpatel** [tirthasheshpatel/Data-Structures-and-Algorithms#3]
Please add deletion operation and documentation for the binary search tree data structure.

**Comment by tacrazymage** [comment]
Hi @tirthasheshpatel  , May I work on this?

**Comment by tirthasheshpatel** [comment]
@tacrazymage Sure!

**Comment by tacrazymage** [comment]
dear @tirthasheshpatel , I've sent a PR for this please feel free to comment or ask for any changes.
